### ISSUE TITLE
Application Form inputs overflow on Full Screen Fix This is Issue

### ISSUE THREAD

**Issue by waleedcodes** [Adedoyin-Emmanuel/alt-school-assignment-1#1]
Application Form inputs overflow on Full Screen Fix This is Issue 
Link Here : https://alt-school-assignment-v1.vercel.app/
![Screenshot_6](https://github.com/Adedoyin-Emmanuel/alt-school-assignment-1/assets/110061477/438064f3-859e-4543-b8bc-8946bfa9ce58)

**Comment by waleedcodes** [comment]
I am Fix This Issue #1 Please check pull request

**Comment by Adedoyin-Emmanuel** [comment]
@waleedcodes Please check my comment on the PR https://github.com/Adedoyin-Emmanuel/alt-school-assignment-1/pull/2#issuecomment-1928702324
